version: "3.8"
services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APP_PORT: 8080
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      SECRET_KEY: ${SECRET_KEY}
    ports:
      - "8080:8080"
    depends_on:
      - pgbouncer
    networks:
      - oauth

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    command: >
      -c max_connections=20000
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - oauth

  pgbouncer:
    image: bitnami/pgbouncer
    restart: always
    ports:
      - 6432:6432
    environment:
      - POSTGRESQL_HOST=postgres
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=killer107
      - POSTGRESQL_DATABASE=postgres
      - PGBOUNCER_POOL_MODE=transaction
      - PGBOUNCER_MAX_CLIENT_CONN=20000
      - PGBOUNCER_DEFAULT_POOL_SIZE=500
      - PGBOUNCER_RESERVE_POOL_SIZE=100
      - PGBOUNCER_RESERVE_POOL_TIMEOUT=30
      - PGBOUNCER_IGNORE_STARTUP_PARAMETERS=extra_float_digits
    networks:
      - oauth

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
    networks:
      - oauth

volumes:
  pg-data:

networks:
  oauth:
    driver: bridge